//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLibraryEditor.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_en_US() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenLibraryEditor.Idiomas.Strings_en_US", typeof(Strings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign in.
        /// </summary>
        internal static string Log_BtnEntrar {
            get {
                return ResourceManager.GetString("Log_BtnEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Francés.
        /// </summary>
        internal static string Log_BtnFrancia {
            get {
                return ResourceManager.GetString("Log_BtnFrancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso invitado.
        /// </summary>
        internal static string Log_BtnInvitado {
            get {
                return ResourceManager.GetString("Log_BtnInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string Log_BtnRegistrarse {
            get {
                return ResourceManager.GetString("Log_BtnRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        internal static string Log_BtnSpain {
            get {
                return ResourceManager.GetString("Log_BtnSpain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        internal static string Log_BtnUSA {
            get {
                return ResourceManager.GetString("Log_BtnUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Log_Contra {
            get {
                return ResourceManager.GetString("Log_Contra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos.
        /// </summary>
        internal static string Log_Error1 {
            get {
                return ResourceManager.GetString("Log_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, introduzca la contraseña.
        /// </summary>
        internal static string Log_Error2 {
            get {
                return ResourceManager.GetString("Log_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, introduzca el usuario.
        /// </summary>
        internal static string Log_Error3 {
            get {
                return ResourceManager.GetString("Log_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, complete todos los campos.
        /// </summary>
        internal static string Log_Error4 {
            get {
                return ResourceManager.GetString("Log_Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantener sesión iniciada.
        /// </summary>
        internal static string Log_LblConectado {
            get {
                return ResourceManager.GetString("Log_LblConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ha olvidado su contraseña? Haga click aquí.
        /// </summary>
        internal static string Log_LlRecuperar {
            get {
                return ResourceManager.GetString("Log_LlRecuperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario o Email.
        /// </summary>
        internal static string Log_Nombre {
            get {
                return ResourceManager.GetString("Log_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Url base de datos.
        /// </summary>
        internal static string Log_Url {
            get {
                return ResourceManager.GetString("Log_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authors.
        /// </summary>
        internal static string Main_Autores {
            get {
                return ResourceManager.GetString("Main_Autores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Main_Buscar {
            get {
                return ResourceManager.GetString("Main_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string Main_Confi {
            get {
                return ResourceManager.GetString("Main_Confi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editoriales.
        /// </summary>
        internal static string Main_Editoriales {
            get {
                return ResourceManager.GetString("Main_Editoriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar libro.
        /// </summary>
        internal static string Main_Eliminar {
            get {
                return ResourceManager.GetString("Main_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Géneros.
        /// </summary>
        internal static string Main_Generos {
            get {
                return ResourceManager.GetString("Main_Generos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        internal static string Main_LinkSesion {
            get {
                return ResourceManager.GetString("Main_LinkSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My library.
        /// </summary>
        internal static string Main_MiBiblioteca {
            get {
                return ResourceManager.GetString("Main_MiBiblioteca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar libro.
        /// </summary>
        internal static string Main_Modificar {
            get {
                return ResourceManager.GetString("Main_Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir nuevo libro.
        /// </summary>
        internal static string Main_NuevoLibro {
            get {
                return ResourceManager.GetString("Main_NuevoLibro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Main_Salir {
            get {
                return ResourceManager.GetString("Main_Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Series.
        /// </summary>
        internal static string Main_Series {
            get {
                return ResourceManager.GetString("Main_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tags.
        /// </summary>
        internal static string Main_Tags {
            get {
                return ResourceManager.GetString("Main_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tittles.
        /// </summary>
        internal static string Main_Titulos {
            get {
                return ResourceManager.GetString("Main_Titulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis autores.
        /// </summary>
        internal static string Main_TTAutores {
            get {
                return ResourceManager.GetString("Main_TTAutores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar libros.
        /// </summary>
        internal static string Main_TTBuscar {
            get {
                return ResourceManager.GetString("Main_TTBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar aplicación.
        /// </summary>
        internal static string Main_TTCerrar {
            get {
                return ResourceManager.GetString("Main_TTCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar aplicación.
        /// </summary>
        internal static string Main_TTConfi {
            get {
                return ResourceManager.GetString("Main_TTConfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis editoriales.
        /// </summary>
        internal static string Main_TTEditoriales {
            get {
                return ResourceManager.GetString("Main_TTEditoriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Library Editor.
        /// </summary>
        internal static string Main_TTFormTitulo {
            get {
                return ResourceManager.GetString("Main_TTFormTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen usuario.
        /// </summary>
        internal static string Main_TTFotoUsuario {
            get {
                return ResourceManager.GetString("Main_TTFotoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis géneros.
        /// </summary>
        internal static string Main_TTGeneros {
            get {
                return ResourceManager.GetString("Main_TTGeneros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click para iniciar sesión.
        /// </summary>
        internal static string Main_TTLink {
            get {
                return ResourceManager.GetString("Main_TTLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo Open Library Editor.
        /// </summary>
        internal static string Main_TTLogo {
            get {
                return ResourceManager.GetString("Main_TTLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximizar.
        /// </summary>
        internal static string Main_TTMaximizar {
            get {
                return ResourceManager.GetString("Main_TTMaximizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimizar.
        /// </summary>
        internal static string Main_TTMinimizar {
            get {
                return ResourceManager.GetString("Main_TTMinimizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurar.
        /// </summary>
        internal static string Main_TTRestaurar {
            get {
                return ResourceManager.GetString("Main_TTRestaurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Main_TTSalir {
            get {
                return ResourceManager.GetString("Main_TTSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis series.
        /// </summary>
        internal static string Main_TTSeries {
            get {
                return ResourceManager.GetString("Main_TTSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis tags.
        /// </summary>
        internal static string Main_TTTags {
            get {
                return ResourceManager.GetString("Main_TTTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis títulos.
        /// </summary>
        internal static string Main_TTTitulos {
            get {
                return ResourceManager.GetString("Main_TTTitulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarme.
        /// </summary>
        internal static string Reg_BtnRegistro {
            get {
                return ResourceManager.GetString("Reg_BtnRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string Reg_Contra {
            get {
                return ResourceManager.GetString("Reg_Contra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir contraseña:.
        /// </summary>
        internal static string Reg_Contra1 {
            get {
                return ResourceManager.GetString("Reg_Contra1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuari@:.
        /// </summary>
        internal static string Reg_Nombre {
            get {
                return ResourceManager.GetString("Reg_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Library Editor - Registro.
        /// </summary>
        internal static string Reg_TituloForm {
            get {
                return ResourceManager.GetString("Reg_TituloForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Url base de datos:.
        /// </summary>
        internal static string Reg_Url {
            get {
                return ResourceManager.GetString("Reg_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to leave us?.
        /// </summary>
        internal static string ShowDialogCerrar {
            get {
                return ResourceManager.GetString("ShowDialogCerrar", resourceCulture);
            }
        }
    }
}
